/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.view;

import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Jelena
 */
public class LoveCalculator extends javax.swing.JFrame {

    /**
     * Creates new form LoveCalculator
     */
    public LoveCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoveCalculator = new javax.swing.JLabel();
        lblHe = new javax.swing.JLabel();
        lblShe = new javax.swing.JLabel();
        btnLove = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        txtEnterHe = new javax.swing.JTextField();
        txtEnterShe = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLoveCalculator.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lblLoveCalculator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoveCalculator.setText("Love calculator");

        lblHe.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lblHe.setText("He:");

        lblShe.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lblShe.setText("She:");

        btnLove.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        btnLove.setText("Love");
        btnLove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoveActionPerformed(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLoveCalculator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEnterHe, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblHe))
                            .addGap(62, 62, 62)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblShe)
                                .addComponent(txtEnterShe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(107, 107, 107)
                            .addComponent(btnLove))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLoveCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShe)
                    .addComponent(lblHe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnterHe, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnterShe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnLove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoveActionPerformed
        String She = txtEnterShe.getText().toLowerCase();
        String He = txtEnterHe.getText().toLowerCase();
        String calculation = countChars(She, He);
        char[] charArray = calculation.toCharArray();
        int[] intArray = new int[charArray.length];
        for (int i = 0; i < charArray.length; i++) {
            intArray[i] = Integer.parseInt("" + charArray[i]);
        }
        List<int[]> asList=Arrays.asList(intArray);

        List<Integer> intList = new ArrayList<Integer>();
        for (int i : intArray) {
            intList.add(i);

        }
        System.out.println(intList);
        List<Integer> list = intList;
        while (list.size() > 2) {
            List<Integer> temp = new ArrayList<>();
            for (int i = 0; i < list.size() - 1; i = i + 2) {
                int result = list.get(i) + list.get(i + 1);
                if (result > 9) {
                    temp.add(result / 10);
                }
                temp.add(result % 10);
            }
            if (list.size() % 2 != 0) {
                temp.add(list.get(list.size() - 1));
            }
            list = temp;
        }
        String result = list.get(0).toString() + list.get(1).toString();
        System.out.println(result);
        lblResult.setText(result + "%");


    }//GEN-LAST:event_btnLoveActionPerformed
    String countChars(String She, String He) {
        String combinedString = She + He;

        String strAllChars = "";
        String strCount = "";
        char tempArray[] = combinedString.toCharArray();
        Arrays.sort(tempArray);
        String sorted = new String(tempArray);
        System.out.println(sorted);
        for (char c1 : sorted.toCharArray()) {
            if (strAllChars.indexOf(c1) < 0) {
                int count = 0;
                for (char c2 : sorted.toCharArray()) {
                    if (c1 == c2) {
                        count++;
                    }
                }
                strAllChars = strAllChars + c1;
                strCount = strCount + String.valueOf(count);
            }
        }
        System.out.println(strCount);

        return strCount;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLove;
    private javax.swing.JLabel lblHe;
    private javax.swing.JLabel lblLoveCalculator;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblShe;
    private javax.swing.JTextField txtEnterHe;
    private javax.swing.JTextField txtEnterShe;
    // End of variables declaration//GEN-END:variables
}
