/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.view;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Jelena
 */
public class LoveCalculator extends javax.swing.JFrame {
     
    /**
     * Creates new form LoveCalculator
     */
    public LoveCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoveCalculator = new javax.swing.JLabel();
        lblHe = new javax.swing.JLabel();
        lblShe = new javax.swing.JLabel();
        btnLove = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        txtEnterHe = new javax.swing.JTextField();
        txtEnterShe = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLoveCalculator.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lblLoveCalculator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoveCalculator.setText("Love calculator");

        lblHe.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lblHe.setText("He:");

        lblShe.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lblShe.setText("She:");

        btnLove.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        btnLove.setText("Love");
        btnLove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoveActionPerformed(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLoveCalculator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEnterHe, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblHe))
                            .addGap(62, 62, 62)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblShe)
                                .addComponent(txtEnterShe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(107, 107, 107)
                            .addComponent(btnLove))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLoveCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShe)
                    .addComponent(lblHe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnterHe, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnterShe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnLove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoveActionPerformed
       String She=txtEnterShe.getText().toLowerCase();
       String He=txtEnterHe.getText().toLowerCase();
       String calculation = countChars(She, He);
       lblResult.setText(shortenNumber(calculation) + "%");
       
       /* String combinedString=She+He;
        
        HashMap<Character, Integer> charCountMap = new HashMap<Character, Integer>();            
             char[] strArray = combinedString.toCharArray(); 
             
             for (char c : strArray) {
                  if (charCountMap.containsKey(c)) { 
                      charCountMap.put(c, charCountMap.get(c) + 1); 
                  }else{
                       charCountMap.put(c, 1); 
                  }
                  
            
        }
           for (Map.Entry entry : charCountMap.entrySet()) { 
         
            
           }*/
        
       
    }//GEN-LAST:event_btnLoveActionPerformed
	String countChars(String She, String He) {
		String combinedString = She + He;

		String strAllChars = "";
		String strCount = "";
		for (char c1 : combinedString.toCharArray()) {
			if (strAllChars.indexOf(c1) < 0) {
				int count = 0;
				for (char c2 : combinedString.toCharArray()) {
					if (c1 == c2) {
						count++;
					}
				}
				strAllChars = strAllChars + c1;
				strCount = strCount + String.valueOf(count);
			}
		}

		return strCount;
	}
        
	String shortenNumber(String str) {
		String shortenString = "";
		if (str.length() >= 2) {
			int int1 = Integer.parseInt(String.valueOf(str.toCharArray() [0]));
			int int2 = Integer.parseInt(String.valueOf(str.toCharArray()[1]));
			shortenString = String.valueOf(int1 + int2) + shortenNumber(str.substring(2, 4));
		} else {
			return str;
		}

		return shortenString;
	}
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLove;
    private javax.swing.JLabel lblHe;
    private javax.swing.JLabel lblLoveCalculator;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblShe;
    private javax.swing.JTextField txtEnterHe;
    private javax.swing.JTextField txtEnterShe;
    // End of variables declaration//GEN-END:variables
}
